services:
  - type: web
    name: profesjonalna-psychoterapia
    env: static
    buildCommand: |
      npm install
      npm run build:static
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /terapeuta/*
        destination: /index.html
      - type: rewrite
        source: /kontakt
        destination: /index.html
      - type: rewrite
        source: /o-nas
        destination: /index.html
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: NODE_VERSION
        value: 18